---
chia-blockchain:
  replicaCount: 1
  image:
    repository: chianetwork/chia-docker #Change to your built docker image url
    pullPolicy: Always
    tag: latest #Change to your built docker image tag
  imagePullSecrets: []
  nameOverride: "" #This will be used as the deployment name
  fullnameOverride: "" #This will be used as the deployment name
  volume:
    storageClassName: '' #Use whatever storage class you want, SSD or better
    size: 500Gi
  chia:
    hostname: 0.0.0.0
    log_level: INFO
    testnet: "false"
    network: "mainnet"
    env: {}
#      mainnet_checkpoint_url: https://torrents.chia.net/databases/mainnet/mainnet.2026-01-01.tar.gz.torrent
#      mainnet_checkpoint_archive: mainnet.2026-01-01.tar.gz
#      testnet_checkpoint_url: https://torrents.chia.net/databases/testnet11/testnet11.2026-01-01.tar.gz.torrent
#      testnet_checkpoint_archive: testnet11.2026-01-01.tar.gz
    ca:
      private_ca_crt: |
        #Paste your CA cert here
      private_ca_key: |
        #Paste your CA key here